### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by bjoss** [powderflask/cmsplugin-menus#2]
Thank you 

I am trying to use your plugin. I've found that in your documentation should be 
cmsplugin_menus.plugins.*, # installs all menu plugins

instead of 
cmsplugin_menu.plugins.*, # installs all menu plugins

regards

Jarek

**Comment by powderflask** [comment]
Thanks Jarek!

fixed.

**Comment by bjoss** [comment]
It still does not work for me I've installed + added to installed_apps 
then syncdb. Is there anything else needed? 
I am getting server errors 

 [Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]     self.load_middleware()
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]   File "/usr/lib/python2.6/dist-packages/django/core/handlers/base.py", line 33, in load_middleware
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]   File "/usr/lib/python2.6/dist-packages/django/utils/functional.py", line 276, in **getattr**
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]     self._setup()
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]   File "/usr/lib/python2.6/dist-packages/django/conf/__init__.py", line 40, in _setup
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]     self._wrapped = Settings(settings_module)
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]   File "/usr/lib/python2.6/dist-packages/django/conf/__init__.py", line 93, in **init**
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]     app_mod = importlib.import_module(app[:-2])
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]   File "/usr/lib/python2.6/dist-packages/django/utils/importlib.py", line 35, in import_module
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]     **import**(name)
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]   File "/usr/local/lib/python2.6/dist-packages/cmsplugin_menus-0.1.1-py2.6.egg/cmsplugin_menus/**init**.py", line 15, in <module>
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]     patch_settings()
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]   File "/usr/local/lib/python2.6/dist-packages/cmsplugin_menus-0.1.1-py2.6.egg/cmsplugin_menus/conf.py", line 27, in patch_settings
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]     if constants.CMSPLUGIN_MENUS_LINK_BLOCK_PLACEHOLDER not in settings.CMS_PLACEHOLDER_CONF \
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]   File "/usr/lib/python2.6/dist-packages/django/utils/functional.py", line 277, in **getattr**
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1]     return getattr(self._wrapped, name)
[Tue Nov 02 15:04:02 2010] [error] [client 127.0.0.1] AttributeError: 'Settings' object has no attribute 'CMS_PLACEHOLDER_CONF'

Sorry I am new to django etc

Thanks

**Comment by powderflask** [comment]
That looks like a bug.  I was having trouble with this, but thought I had it resolved - I'll look into it again.  For now, try adding:
CMS_PLACEHOLDER_CONF = {} 
to your settings file - that should patch the issue for you.  Let me know.
